services:
  postgresql-dev:
    container_name: postgresql-dev
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "15432:5432/tcp"
    environment:
      - POSTGRES_DB=db-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    stdin_open: true
    tty: true
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres
    depends_on:
      - postgresql-dev

  redis:
    container_name: redis
    image: redis/redis-stack:latest
    restart: unless-stopped
    ports:
      - "6379:6379" # Redis port
      - "8001:8001" # RedisInsight port
    volumes:
      - redis_data:/data
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
